---
{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: aeraki
  namespace: {{ .Release.Namespace }}
  labels:
    app: aeraki
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: aeraki
{{- end }}
